//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_KaiOKen_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportBill
    {
        public int ID_HD { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public string USERNAME { get; set; }
        public string ID_GIAY { get; set; }
        public string TENLOAIGIAY { get; set; }
        public long GIA { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public int TONGTIEN { get; set; }
    }
}
