CREATE DATABASE [QuanLyShopBanGiay]
GO


USE [QuanLyShopBanGiay]
GO

--TABLE ACCOUNT
CREATE TABLE [dbo].[ACCOUNT]
(
	[DisplayName] [nvarchar](100) NOT NULL,
	[UserName] [nvarchar](100) PRIMARY KEY,
	[Password] [nvarchar](100) NOT NULL,
	[Ca] [int] NULL,
	[TYPE] [int] NULL,
	[SoDienThoai] [nvarchar](100) NULL,
)
GO

---TABLE CATAROGRY
CREATE TABLE [dbo].[Catarogry](
	[ID_LoaiGiay] [int] IDENTITY(1,1) PRIMARY KEY,
	[TenLoaiGiay] [nvarchar](100) NOT NULL,
)

----THONGTINGIAY

CREATE TABLE [dbo].[THONGTINGIAY](
	[ID_Giay] [nvarchar](100) PRIMARY KEY,
	[TenSanPham] [nvarchar](100) NOT NULL,
	[Gia] [bigint] NOT NULL,
	[ID_LoaiGiay] [int] FOREIGN KEY REFERENCES [dbo].[Catarogry](ID_LoaiGiay),
	[Status] [int] NULL,
)
GO


--- MA KHUYEN MAI
CREATE TABLE [dbo].[KHACHHANG]
(
	[SDTKM] NVARCHAR(100) PRIMARY KEY,
)
GO

--- SAN PHAM TANG KEM
CREATE TABLE [dbo].[SPBL](
	[ID_SPBL] [int] IDENTITY PRIMARY KEY,
	[Ten_SPKM] [nvarchar](100) NOT NULL,
	[Gia_banle] [bigint] NOT NULL,
	[Soluong] [int] NOT NULL
)
GO

---HOADON
CREATE TABLE [dbo].[HOADON](
	[ID_HD] [int] IDENTITY(1,1) PRIMARY KEY,
	[NGAYTAO] [date] NOT NULL,
	[USERNAME] [nvarchar](100) FOREIGN KEY REFERENCES [dbo].[Account](USERNAME),
	[TONGTIEN] [int] NOT NULL,
) 
GO
------DISCOUNT
CREATE TABLE [dbo].[DISCOUNT]
(
	ID_DISCOUNT INT IDENTITY PRIMARY KEY,
	[DISCOUNTLV] [float],
)
GO
--CHI TIET HOA DON
CREATE TABLE [dbo].[CHITIETHOADON](
	[ID_CTHD] [int] IDENTITY(1,1) PRIMARY KEY,
	[ID_HD] [int] FOREIGN KEY REFERENCES [dbo].[HOADON](ID_HD),
	[ID_GIAY] [nvarchar](100) FOREIGN KEY REFERENCES [dbo].[THONGTINGIAY](ID_Giay),
	[ID_SPBL] [int] FOREIGN KEY REFERENCES [dbo].[SPBL](ID_SPBL),
	[ID_DISCOUNT] [int] FOREIGN KEY REFERENCES [dbo].[DISCOUNT](ID_DISCOUNT),
 )
GO
ALTER TABLE [dbo].[CHITIETHOADON] ADD SOLUONGSPBL INT
--DISCOUNT

SELECT*fROM THONGTINGIAY
---
INSERT INTO ACCOUNT VALUES(N'DUNG',N'dungtran9x225',N'zxcvbn',0,1,N'01682130203')
SELECT*FROM DISCOUNT WHERE ID_DISCOUNT = (SELECT MAX(ID_DISCOUNT) FROM DISCOUNT)
SELECT*FROM CHITIETHOADON
SELECT*fROM SPBL
UPDATE SPBL SET SOLUONG = 200 WHERE ID_SPBL =1
SELECT ID_CTHD, A.ID_HD,E.ID_GIAY,TEN_SPKM,DISCOUNTLV,GIA,TenLoaiGiay FROM HOADON A, CHITIETHOADON B, DISCOUNT C, SPBL D, THONGTINGIAY E, Catarogry F
WHERE A.ID_HD=B.ID_HD AND B.ID_DISCOUNT=C.ID_DISCOUNT AND B.ID_SPBL=D.ID_SPBL AND E.ID_Giay=B.ID_GIAY AND E.ID_LoaiGiay=F.ID_LoaiGiay


SELECT A.ID_SPBL, SOLUONGSPBL,TEN_SPKM FROM CHITIETHOADON A, SPBL B WHERE A.ID_SPBL=B.ID_SPBL AND ID_HD=32
delete from SPBL where ID_SPBL=2
UPDATE SPBL SET Soluong=200 WHERE ID_SPBL=2
SELECT COUNT(B.ID_CTHD) AS [SOLUONG],NGAYTAO FROM HOADON A, CHITIETHOADON B WHERE  A.ID_HD = B.ID_HD AND NGAYTAO > '1/1/2018' AND NGAYTAO<'2/1/2018' GROUP BY NGAYTAO

DELETE FROM CHITIETHOADON WHERE ID_CTHD>17
SELECT Ten_SPKM,SOLUONGSPBL,Gia_banle FROM CHITIETHOADON A, SPBL B WHERE ID_HD=42 AND A.ID_SPBL=B.ID_SPBL